const words = [
  { word: "к_ртина", answers: ["а"], fullWord: "картина" },
  { word: "дев_чка", answers: ["о"], fullWord: "девочка" },
  { word: "н_деля", answers: ["е"], fullWord: "неделя" },
  { word: "жав_р_н_к", answers: ["о", "о", "о"], fullWord: "жаворонок" },
  { word: "к_л_ндар_", answers: ["а", "е", "ь"], fullWord: "календарь" },
  { word: "ч_л_век", answers: ["е", "о"], fullWord: "человек" },
  { word: "кв_ртира", answers: ["а"], fullWord: "квартира" },
  { word: "м_тро", answers: ["е"], fullWord: "метро" },
  { word: "п_л_то", answers: ["а", "ь"], fullWord: "пальто" },
  { word: "__тобус", answers: ["а", "в"], fullWord: "автобус" },
  { word: "кр_пива", answers: ["а"], fullWord: "крапива" },
  { word: "тр_мвай", answers: ["а"], fullWord: "трамвай" },
  { word: "к_стёр", answers: ["о"], fullWord: "костёр" },
  { word: "п_суда", answers: ["о"], fullWord: "посуда" },
  { word: "фу_бол", answers: ["т"], fullWord: "футбол" },
  { word: "р_бина", answers: ["я"], fullWord: "рябина" },
  { word: "к_рзина", answers: ["о"], fullWord: "корзина" },
  { word: "вет_р", answers: ["е"], fullWord: "ветер" },
  { word: "_гурец", answers: ["о"], fullWord: "огурец" },
  { word: "к_нфета", answers: ["о"], fullWord: "конфета" },
  { word: "к_р_дор", answers: ["о", "и"], fullWord: "коридор" },
  { word: "б_лот_", answers: ["о", "о"], fullWord: "болото" },
  { word: "к_ртоф_ль", answers: ["а", "е"], fullWord: "картофель" },
  { word: "м_рко_ь", answers: ["о", "в"], fullWord: "морковь" },
  { word: "_рех", answers: ["о"], fullWord: "орех" },
  { word: "п_м_дор", answers: ["о", "и"], fullWord: "помидор" },
  { word: "рю_зак", answers: ["к"], fullWord: "рюкзак" },
  { word: "с_п_ги", answers: ["а", "о"], fullWord: "сапоги" },
  { word: "с_бака", answers: ["о"], fullWord: "собака" },
  { word: "т_л_виз_р", answers: ["е", "е", "о"], fullWord: "телевизор" },
  { word: "т_вар_щ_", answers: ["о", "и", ""], fullWord: "товарищ" },
  { word: "ур_жай", answers: ["о"], fullWord: "урожай" },
  { word: "ябл_ня", answers: ["о"], fullWord: "яблоня" },
  { word: "ап__тит", answers: ["п", "е"], fullWord: "аппетит" },
  { word: "бер_г", answers: ["е"], fullWord: "берег" },
  { word: "дят_л", answers: ["е"], fullWord: "дятел" },
  { word: "л_донь", answers: ["а"], fullWord: "ладонь" },
  { word: "пш_ница", answers: ["е"], fullWord: "пшеница" },
  { word: "с_лат", answers: ["а"], fullWord: "салат" },
  { word: "с_ница", answers: ["и"], fullWord: "синица" },
  { word: "см_род_на", answers: ["о", "и"], fullWord: "смородина" },
  { word: "суб_ота", answers: ["б"], fullWord: "суббота" },
  { word: "ул_ца", answers: ["и"], fullWord: "улица" },
  { word: "_ппетит", answers: ["а"], fullWord: "аппетит" },
  { word: "ябл_к_", answers: ["о", "о"], fullWord: "яблоко" },
];
